In [51]:
import math
import numpy as np
import pandas as pd

## Array indexing and slicing

In [52]:

a = np.array([[7 ,2,5 ,9 ],[3 ,4,11,13 ],[5 ,6,7.5,9 ],[15 ,8,5.2,9.3]])

In [53]:
a

array([[ 7. ,  2. ,  5. ,  9. ],
       [ 3. ,  4. , 11. , 13. ],
       [ 5. ,  6. ,  7.5,  9. ],
       [15. ,  8. ,  5.2,  9.3]])

In [54]:
a[1]  # One dimensional sub array

array([ 3.,  4., 11., 13.])

In [55]:
a[:,3]

array([ 9. , 13. ,  9. ,  9.3])

In [56]:
a[1,2] #Accessing single element

11.0

In [57]:
a[1:,2:] #slicing across multiple dimensions

array([[11. , 13. ],
       [ 7.5,  9. ],
       [ 5.2,  9.3]])

In [58]:
a[[1,2,3],[0,1,2]]    #Advanced indexing

array([3. , 6. , 5.2])

In [68]:
print('BOOLEAN INDEXING')
copy=a
copy[copy<7]=False
copy[copy>7]=True
copy
                #boolean indexing


BOOLEAN INDEXING


array([0, 0, 0, ..., 1, 1, 1])

In [69]:
print('BOOLEAN INDEXING')
a = np.array([10, 40, 80, 50, 100]) 
a[a>50]



BOOLEAN INDEXING


array([ 80, 100])

## Handling Non existing values

In [59]:
a=np.array([[12,np.nan, 1,0,1],[2,17,np.nan,5,1],[1,8,14,10,1],[6,7,1,9,1],[12,np.nan,1,np.nan,np.nan]])

In [60]:
a

array([[12., nan,  1.,  0.,  1.],
       [ 2., 17., nan,  5.,  1.],
       [ 1.,  8., 14., 10.,  1.],
       [ 6.,  7.,  1.,  9.,  1.],
       [12., nan,  1., nan, nan]])

In [49]:
np.nansum(a)

110.0

In [65]:
b = np.array([[5, 5],[4, 5],[16, 4]]) 
sumrow = b.sum(-1) 
b[sumrow%10==0] 


array([[ 5,  5],
       [16,  4]])

In [66]:
print('Handling non-existing values')
h=[23,64,12,78,34,68,2,85,21,48,57,89]
h.append(np.nan)
h


Handling non-existing values


[23, 64, 12, 78, 34, 68, 2, 85, 21, 48, 57, 89, nan]

In [67]:
h=[np.nan,21,32,45,68,78,np.nan,42,6,np.nan,98,22,84,np.nan,1,34,75,np.nan,np.nan]
np.nan_to_num(h)



array([ 0., 21., 32., 45., 68., 78.,  0., 42.,  6.,  0., 98., 22., 84.,
        0.,  1., 34., 75.,  0.,  0.])

## Compare runtime behavior

In [70]:

print('COMPARING RUNTIME BEHAVIOUR')
a=[]
%time for i in range(0,10000) : a.append(i)

%time a=np.arange(0,10000)



COMPARING RUNTIME BEHAVIOUR
Wall time: 998 µs
Wall time: 0 ns
